spring:
  application:
    name: shoe-seckill-user

  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: com.zhao.shoeSeckill.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath*:com.zhao.shoeSeckill.persistence/*.xml

server:
  port: 8081

#dubbo配置
embedded:
  zookeeper:
    port: 2181
dubbo:
  scan:
    base-packages: com.zhao.shoeSeckill.service
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 12345
    threads: 800
    threadpool: cached
    dispatcher: message
  registry:
    check: true
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}

#redis:
#  host: 121.40.220.104
#  port: 6379
#  timeout: 1000
#  poolMaxTotal: 1000
#  poolMaxIdle: 500
#  poolMaxWait: 500

logging:
  level:
    root: info
    com.zhao.shoeSeckill: debug
  path: logs/
  file: shoeSeckill.log
    max-history: 3
